---
- name: update cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  sudo: yes

- name: install required package
  apt:
    name: ['apache2', 'mysql-server', 'python-mysqldb']
    state: present
  sudo: yes

